### ISSUE TITLE
Issue with Flight Order Management Cancel

### ISSUE THREAD

**Issue by anthonyroux** [amadeus4dev/amadeus-android#21]
I have an issue with the cancel API. When success the API returns a 204 - no content (and doesn't return anything), I think that could be the issue.

```kotlin
    @Test
    fun `Booking FlightCreateOrder with object, retrieve and delete`() = runBlocking {
        // Create fake traveler
        val traveler = Traveler(
            id = "1",
            dateOfBirth = "2000-04-14",
            name = Name("JORGE", "GONZALES"),
            contact = Contact(
                listOf(
                    Phone(
                        countryCallingCode = "33",
                        number = "675426222",
                        deviceType = "MOBILE"
                    )
                )
            ),
            documents = listOf(
                Document(
                    documentType = "PASSPORT",
                    number = "480080076",
                    expiryDate = "2022-10-11",
                    issuanceCountry = "ES",
                    nationality = "ES",
                    holder = true
                )
            )
        )

        val flightOffers = amadeus.shopping.flightOffersSearch.get(
            originLocationCode = "NCE",
            destinationLocationCode = "PAR",
            departureDate = "2020-11-01",
            returnDate = "2020-11-08",
            adults = 1,
            max = 3
        )
        assert(flightOffers?.succeeded ?: false)
        if (flightOffers is Success) {
            val pricing =
                amadeus.shopping.flightOffersSearch.pricing.post(flightOffers.data.first())
            assert(pricing?.succeeded ?: false)

            if (pricing is Success) {
                val order = amadeus.booking.flightOrders.post(
                    flightPrice = pricing.data,
                    travelers = listOf(traveler)
                )

                assert(order?.succeeded ?: false)
                if (order is Success) {
                    order.data.id?.let { amadeus.booking.flightOrder(it).get()?.succeeded } ?: false
                    order.data.id?.let { amadeus.booking.flightOrder(it).delete() is Success} ?: false
                }
            }
        }
    }
```

> java.lang.IllegalArgumentException: Unable to create converter for com.amadeus.android.ApiResult$Success<kotlin.Unit>
>     for method BookingApi.cancelFlightOrder
> 
> 	at retrofit2.Utils.methodError(Utils.java:53)
> 	at retrofit2.HttpServiceMethod.createResponseConverter(HttpServiceMethod.java:115)
> 	at retrofit2.HttpServiceMethod.parseAnnotations(HttpServiceMethod.java:82)
> 	at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:37)
> 	at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:192)
> 	at retrofit2.Retrofit$1.invoke(Retrofit.java:149)
> 	at com.sun.proxy.$Proxy22.cancelFlightOrder(Unknown Source)
> 	at com.amadeus.android.booking.FlightOrder$delete$2.invokeSuspend(FlightOrder.kt:31)
> 	at com.amadeus.android.booking.FlightOrder$delete$2.invoke(FlightOrder.kt)
> 	at com.amadeus.android.BaseApi$safeApiCall$2.invokeSuspend(BaseApi.kt:24)
> 	at |b|b|b(Coroutine boundary.|b(|b)
> 	at com.amadeus.android.service.AmadeusTest$Booking FlightCreateOrder with object and delete$1.invokeSuspend(AmadeusTest.kt:363)
> Caused by: java.lang.IllegalArgumentException: Unable to create converter for com.amadeus.android.ApiResult$Success<kotlin.Unit>
>     for method BookingApi.cancelFlightOrder
> 	at retrofit2.Utils.methodError(Utils.java:53)
> 	at retrofit2.HttpServiceMethod.createResponseConverter(HttpServiceMethod.java:115)
> 	at retrofit2.HttpServiceMethod.parseAnnotations(HttpServiceMethod.java:82)
> 	at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:37)
> 	at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:192)
> 	at retrofit2.Retrofit$1.invoke(Retrofit.java:149)
> 	at com.sun.proxy.$Proxy22.cancelFlightOrder(Unknown Source)
> 	at com.amadeus.android.booking.FlightOrder$delete$2.invokeSuspend(FlightOrder.kt:31)
> 	at com.amadeus.android.booking.FlightOrder$delete$2.invoke(FlightOrder.kt)
> 	at com.amadeus.android.BaseApi$safeApiCall$2.invokeSuspend(BaseApi.kt:24)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
> Caused by: java.lang.IllegalArgumentException: Platform class kotlin.Unit requires explicit JsonAdapter to be registered
> for class kotlin.Unit data
> for com.amadeus.android.ApiResult$Success<kotlin.Unit>
> 	at com.squareup.moshi.Moshi$LookupChain.exceptionWithLookupStack(Moshi.java:349)
> 	at com.squareup.moshi.Moshi.adapter(Moshi.java:150)
> 	at com.amadeus.android.ApiResult_SuccessJsonAdapter.<init>(ApiResult_SuccessJsonAdapter.kt:32)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at com.squareup.moshi.internal.Util.generatedAdapter(Util.java:540)
> 	at com.squareup.moshi.StandardJsonAdapters$1.create(StandardJsonAdapters.java:60)
> 	at com.squareup.moshi.Moshi.adapter(Moshi.java:138)
> 	at com.squareup.moshi.Moshi.adapter(Moshi.java:98)
> 	at retrofit2.converter.moshi.MoshiConverterFactory.responseBodyConverter(MoshiConverterFactory.java:91)
> 	at com.amadeus.android.tools.WrapperConverterFactory.responseBodyConverter(WrapperConverterFactory.kt:18)
> 	at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:352)
> 	at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:335)
> 	at retrofit2.HttpServiceMethod.createResponseConverter(HttpServiceMethod.java:113)
> 	... 14 more
> Caused by: java.lang.IllegalArgumentException: Platform class kotlin.Unit requires explicit JsonAdapter to be registered
> 	at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:65)
> 	at com.squareup.moshi.Moshi.adapter(Moshi.java:138)
> 	... 28 more
>

**Comment by pietrini** [comment]
Fixed with release 1.0.0 ?
